In [20]:
import torch
import torch.nn as nn

Token Id's for the words

In [21]:
inp_ids = torch.tensor([2, 5, 4, 1])

Generating Embedding Weight Matrix

In [22]:
vocab_size = 6
out_dims = 3

torch.manual_seed(123)
embedding_layer = nn.Embedding(vocab_size, out_dims)

In [23]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [24]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [25]:
print(embedding_layer(inp_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-2.8400, -0.7849, -1.4096],
        [-1.1589,  0.3255, -0.6315],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
